language: node_js
os:
  - linux
cache:
  yarn: true
  npm: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add parcel-bundler

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn build:example

after_success: yarn coverage

jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: '$GITHUB_TOKEN'
        skip_cleanup: true
        on:
          tags: true
    - stage: npm release
      node_js: '11.10.1'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        on: master

branches:
  only:
    - master
    - feature/npm-deploy
